### ISSUE TITLE
Collection data structure

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-dash#15]
A collection is a bag of entities (datasets, visualisations and dashboards). Note in particular that collections **can't** contain other collections.

On the client collections are located at the root of the redux state tree:

```javascript
{
  collections: { 
  /* 
   * A map from collection id to collection
   */
  }
}
```

Where each collection is represented as

```javascript
{
  id: 54234234
  name: "Collection Name"
  // A list of unique entity ids
  entities: [435235234,454532342,4323524634,324325235]
  created: 1454254403445
  modified: 1454254403445
}
```

@gabemart, @kardan feedback welcome as usual

**Comment by kardan** [comment]
Would you not need more data on each item in the collection? As in
```javascript
entities: [{"id": "435235234", "type": "dataset", "name": ".."},{"id": ...} ...]
```
Would you not otherwise need to query each of those entities for what icon to use & the entity name.

**Comment by jonase** [comment]
@kardan On the client I would rather keep things as normalized as possible and look up entity specifics by key from another "index" in the (client side) store. Otherwise we'll need to keep track of all the duplications when we change things.

**Comment by kardan** [comment]
Ok, got it.

**Comment by iperdomo** [comment]
Can we close this issue?

**Comment by jonase** [comment]
yes, for now.
