### ISSUE TITLE
Webpack configuration for development & production

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-dash#26]
We're using webpack to support the front end development (jsx/sass compilation etc.) and it's working really well. In addition we support ["Hot Module Replacement (HMR)"](https://github.com/webpack/docs/wiki/hot-module-replacement-with-webpack) which is great for the front end dev experience. 

In this issue we'll collect problems (& hopefully their solutions) in trying to keep using the same setup even as the rest of Akvo Dash evolves.

For example, we need to run the [`webpack-dev-server`](https://webpack.github.io/docs/webpack-dev-server.html) in order to support HMR which means that it is not enough to run only the Clojure backend server during front-end development. We also need to make sure that we have a straight forward production build that puts the static assets built by webpack in all the right places so that (in production) the clojure server can serve them to the client.

**Comment by jonase** [comment]
@kardan we'll need to figure out how to configure the backend to serve `index.html` for all the different (and future) client side routes. One approach could be to explitly list them in `:aliases` in `system.clj`, something like 

```clojure
{:aliases  {"/" "/index.html"
            "/library/*" "/index.html" ;; perhaps :aliases doesn't support wildcards??
            "/dataset/*" "/index.html"
                ...}} 
```

This seems a bit gross so maybe there's a better way.

@iperdomo  Or perhaps it's better to do this in `nginx` config?

**Comment by kardan** [comment]
(Mis)use catch all?
