### ISSUE TITLE
HTTP api

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-dash#33]
This issue will try to specify the HTTP api interface between the client dashboard and the backend.

# TOC
* [datasets](#datasets)
* [library](#library)
* [visualisations](#visualisations)

# <a name="datasets"></a> /datasets

### Create a new dataset from a data source 

```
POST /api/datasets
{
  "name": "My Dataset"
  "source" {
    "kind": "LINK"
    "url": "http://..."
  }
}

returns:

{
  "id": "de305d54-75b4-431b-adb2-eb6b9e546014"
  "status": "PENDING"
  "name": "My Dataset"
}
```

Since the dataset is fetched & prepared asynchronously on the backend the dataset will not be immediately available, and therefor in a `PENDING` state.

### Get a single dataset

```
GET /api/datasets/:id

Returns one of
{
  "id": "de305d54-75b4-431b-adb2-eb6b9e546014"
  "status": "PENDING"
  "name": "My Dataset"
}

{
  "id": "de305d54-75b4-431b-adb2-eb6b9e546014"
  "status": "FAILURE"
  "reason": "Could not find dataset on remote server (404)"
  "name": "My Dataset"
}

{
  "id": "de305d54-75b4-431b-adb2-eb6b9e546014"
  "status": "OK"
  "name": "My Dataset"
  "columns": [
    {
      "title": "Column 1",
      "type": "NUMBER",
      "values": [1, 2, 3]
    },
    {
      "title": "Column 2",
      "type": "STRING",
      "values" ["foo", "bar", "baz"]
    },
    {
      "title": "Column 3",
      "type": "DATE",
      "format": "dd-mm-yyyy",
      "values": [1454036337, 1454036370, 1454036402]
    }
  ],
}
```

### Get data source information

Once the dataset has been imported the data source is seldom needed. You can still get the data source definition with

``` 
GET /datasets/:id/source
{
  "kind": "LINK"
  "url": "http://..."
}
```

###  Get imports 
List only pending by default?
``` 
GET /datasets/:id/imports
[{
  "id": "..",
  "status: "OK"
 } ,{
  "id": "..",
  "status: "PENDING"
}]
```

### Cancel pending dataset
```
// TODO
```

### Delete dataset
```
DELETE /datasets/:id

Set the dataset to disabled and return one of alts
{
  "id": "de305d54-75b4-431b-adb2-eb6b9e546014",
  "status":  "DELETED",
  "enabled": false
}

{
  "id": "de305d54-75b4-431b-adb2-eb6b9e546014",
  "status":  "FAILURE",
  "enabled": true
}

or only return status codes and empty body e.g.
POST /datasets/:id success -> 200/204
POST /datasets/:id failure -> 404, 401, 5**?
```

# <a name="library"></a> /library

The `/library` endpoint is meant to support the "library" view which is a listing of all the datasets, visualisations and dashboards. It is often the first thing the user sees when using DASH.

For the first iteration we can probably get away with a single `/api/library` endpoint but in future iterations we need to tackle things like pagination, sorting, etc.

### Get the library entities

```
GET /api/library
{
  // The datasets should not contain the actual data. 
  // The "metadata" is enough: `name`, `status`, `created`, `modified` etc.
  "datasets": [
    // array of datasets
  ],
  "visualisations": [
    // array of visualisations
  ],
  "dashboards": [] // Always empty in the first iteration
}
```
# <a name="visualisations"></a> /visualisations

```
POST /api/visualisations
{
  "name": "My visualisation", 
  "spec" {}
}
Return:
{
  "id": "de305d54-75b4-431b-adb2-eb6b9e546014",
  "name": "My visualisation",
  "spec" {}
}
```

```
GET /visualisations/:id
returns
{
  "id": "56cc2261-af64-421a-bc9d-635e54ae73c4",
  "name": "My visualisation",
  "spec": {},
  "created": 1456218721818,
  "modified": 1456231792074
}

PUT /visualisations/:id 
returns
{
  "status": "OK"
}

DELETE /visualisations/:id 
returns
{
  "status": "OK"
}

```

**Comment by Lynngre** [comment]
Aren't we starting DASH as https:// from the start?

**Comment by Lynngre** [comment]
@Lynn TLS/SSL is a layer of secured communication used for a protocol like HTTP
 that means, we speak "http" between client and server

**Comment by kardan** [comment]
Since the "source" is probably only needed for things like "reconfiguring a failing import" we could move that to /datasets/:id/source. So if we want to reconfigure we could just hit that limited endpoint.

**Comment by kardan** [comment]
This is implemented (more of less) - closing.
