### ISSUE TITLE
Authentication with keycloak

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-dash#38]
We are using [keycloak](http://keycloak.jboss.org/) version 1.7.0 for authentication (and in the future authorization). I've been unable to find online documentation for this specific version but the docs can be [downloaded](http://keycloak.jboss.org/downloads-archive.html?dir=0%3D1.7.0.Final%3B).

The first iteration will require a user to authenticate with our keycloak server before accessing the dashboard.

**Comment by brianmingus** [comment]
@jonase any chance you can spend a few minutes fixing this issue?https://github.com/jonase/learndatalogtoday/issues/28
