### ISSUE TITLE
Configurize file storage

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-dash#52]
At the moment files are stored in /tmp/akvo/dash, should  be a config. This applies to both resumed and the other files.

**Comment by iperdomo** [comment]
We don't want to rely on having the uploaded data on disk, we should _move_ it to the database

**Comment by kardan** [comment]
@iperdomo @jonase Can we kill this issue?

**Comment by jonase** [comment]
@kardan I think so. We still store uploaded files on disk but immediately move the content to postgresql. Uploading to s3 or a similar service can be a future enhancement if we find it necessary.
