### ISSUE TITLE
Discuss deletion of datasets?

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-dash#69]
At the moment we don't allow the user to delete datasets.

Since entities (other datasets?, visualisations, dashboards) rely (depends) on datasets it's not clear how we want to implement this. One could imagine
- Don't allow to delete - already implemented :-)
- archive - (a visualisation depending on the archive would still render but the dataset would not be enabled for new visualisations.
- cascading - tricky? Should a users delete action, remove another uses visualisation that depends on that dataset? Also tricky to implement in a performant way in our current setup. This since the dataset ref is inside the jsonb filed. Maybe this is not as slow as I'm afraid of but I guess it would require Postgres 9.5. One could also move the dataset ref outside the spec into it's own field (if that helps)

**Comment by kardan** [comment]
After a quick chat it seems like "ask user and then cascade might be a likely contender.

**Comment by iperdomo** [comment]
@kardan can we close this? The discussion is "done" ? I guess that foreign keys with `ON DELETE CASCADE` are implemented, right?

**Comment by kardan** [comment]
I think the discussion is done and closable. But I have not tested how things behave (with visualisations) if we delete. But this issue was about the discussion so let's close this.
